#!/bin/bash

# Check if at least one parameter was provided
if [ "$#" -lt 1 ]; then
    echo "Uso: ccd [-L|-P] <ruta>"
    exit 1
fi
actual=$(pwd)

# Initialize an empty string for the options
opciones=""
ruta=""

# Iterates over the parameters until a path is found
for parametro in "$@"; do
    # Check if the parameter is an option
    if [[ $parametro == -* ]]; then
        # Add the option to the options string
        opciones="$opciones $parametro"
    else
        # The parameter is a path, so exit the loop
        ruta=$parametro
        break
    fi
done

# Invokes the cd command with the options and the path
if [ -z "$opciones" ]; then
    echo "cd $ruta"
    source cd $ruta
else
    echo "cd $opciones $ruta"
    source cd $opciones $ruta
fi

# Check if the cd command was successful
if [ "$?" -eq 0 ]; then
    # Obtain the absolute path after changing the directory
    ruta_absoluta=$(pwd)

    # Invokes the clog script with the command and the absolute path
    $actual/clog "cd" "$ruta_absoluta"
else
    echo "ccd: no se pudo cambiar al directorio: $ruta"
fi