#!/bin/bash

#########################################AUTORES#############################################
# - Para ejecutar el comando en el hilo principal se debe hacer uso de la instrucción source
# - Uso: source cls [Opciones] <ruta>
#############################################################################################

validParameter=false # Flag to check if the provided parameter is valid

# Check if files or directories exist, then invoke the clog script
for parametro in "$@"; do
    if [ -e "$parametro" ]; then
        # Gets the absolute path of the provided parameter
        ruta_absoluta=$(readlink -f "$parametro")

        validParameter=true

        # Invokes the clog script with the command and the absolute path
        clog "ls" "$ruta_absoluta"
    fi
done

# If the provided parameter is not valid, invoke the clog script with the command and the current directory
if [ $validParameter == false ]; then
    clog "ls" "$(pwd)"
fi

# Invokes the ls command with the provided parameters
ls "$@"
