#!/bin/bash

#########################################AUTORES#############################################
# - Para ejecutar el comando en el hilo principal se debe hacer uso de la instrucción source
# - Uso: source crm [Opciones] <ruta>
#############################################################################################

# Check if at least one parameter was provided
if [ "$#" -lt 1 ]; then
    echo "Uso: crm [Opciones] <ruta>"
    exit 1
fi


for parametro in "$@"; do
    if [ -e "$parametro" ]; then
        # Gets the absolute path of the provided parameter
        ruta_absoluta=$(readlink -f "$parametro")

        current_dir=$(pwd)
        
        # Invokes the clog script with the command and the absolute path
        $current_dir/clog "rm" "$ruta_absoluta"
    fi
done

# Invoke the rm command with the provided parameters
rm "$@"
