#!/bin/bash

# Obtains the current directory
directorio_actual=$(pwd)

# Define the syslog directory
sylogDir="/var/log/syslog"

# Define the display format
# %-4s: Aligns the text to the left with a width of 4 characters
# %-6s: Aligns the text to the left with a width of 6 characters
# %s: Prints the text
formato="%-4s %-6s %-6s %s\n"

# Prints the headers
printf "$formato" "id" "user" "action" "path"

# Check if a parameter was provided
if [ "$#" -eq 1 ]; then
    # Filters the events by the provided action
    grep "$1" $sylogDir | while read -r linea; do
        # Extracts the fields of the line
        id=$(echo $linea | cut -d' ' -f1)
        user=$(echo $linea | cut -d' ' -f2)
        action=$(echo $linea | cut -d' ' -f3)
        path=$(echo $linea | cut -d' ' -f4-)

        # Checks if the event occurred in the current directory or in a subdirectory
        if [[ $path == $directorio_actual* ]]; then
            # Prints the event
            printf "$formato" "$id" "$user" "$action" "$path"
        fi
    done
else
    # Show all events
    cat $sylogDir | while read -r linea; do
        # Extracts the fields of the line
        id=$(echo $linea | cut -d' ' -f1)
        user=$(echo $linea | cut -d' ' -f2)
        action=$(echo $linea | cut -d' ' -f3)
        path=$(echo $linea | cut -d' ' -f4-)

        # Checks if the event occurred in the current directory or in a subdirectory
        if [[ $path == $directorio_actual* ]]; then
            # Prints the event
            printf "$formato" "$id" "$user" "$action" "$path"
        fi
    done
fi