#!/bin/bash

# Check if the correct number of arguments is provided
if [ $# -ne 2 ]; then
    echo "Uso: $0 old_id new_id"
    exit 1
fi

bck="$HOME/bckdir"
files="$bck/files"
old_id=$1
new_id=$2

# Verify if the old id exists in mypaths.txt and get the associated path
old_path=$(grep "^$old_id," "$bck/mypaths.txt" | cut -d ',' -f 2)

if [ -z "$old_path" ]; then
    echo "El identificador $old_id no existe en mypaths.txt"
    exit 1
fi

# Verify if the new id already exists in mypaths.txt
if grep -q "^$new_id," "$bck/mypaths.txt"; then
    echo "El nuevo identificador $new_id ya existe en mypaths.txt"
    exit 1
fi

# Change the id in mypaths.txt
sed -i "s/^$old_id,/$new_id,/" "$bck/mypaths.txt"
echo "Se ha cambiado el identificador $old_id por $new_id en mypaths.txt"

# Verify if the id file exists in the files directory
if [ -f "$files/$old_id" ]; then
    # Change the name of the id file
    mv "$files/$old_id" "$files/$new_id"
    echo "Se ha cambiado el identificador $old_id por $new_id en $files"
else
    echo "El archivo $old_id no existe en el directorio $files"
    exit 1
fi

# Check if a symbolic link exists pointing to old_id
if [ -L "$old_path" ]; then
    link_target=$(readlink "$old_path")
    if [ "$link_target" == "$files/$old_id" ]; then
        # Change the target of the symbolic link
        ln -sfT "$files/$new_id" "$old_path"
        echo "Se ha cambiado el enlace simbólico de $old_id a $new_id en $old_path"
    fi
else
    echo "No se encontró ningún enlace simbólico apuntando a $old_id en $old_path"
    exit 1
fi

exit 0