#!/bin/bash

# Verify that an argument has been passed
if [ $# -ne 1 ]; then
    echo "Uso: $0 id"
    exit 1
fi

id_borrar=$1
bck="$HOME/bckdir"
files="$bck/files"

# Verify if the file exists in the backup directory
if [ ! -e "$files/$id_borrar" ]; then
    echo "El archivo $id_borrar no existe en el directorio de copia de seguridad."
    exit 1
fi
	
my_path=$(grep "^$id_borrar," "$bck/mypaths.txt" | cut -d ',' -f 2)

if [ -z "$my_path" ]; then
    echo "El identificador $id_borrar no existe en $bck/mypaths.txt"
    exit 1
fi

# Delete the line that contains the id in mypaths.txt
sed -i "/$id_borrar,/d" "$bck/mypaths.txt"

# Verify if the symbolic link exists, to remove it
if [ -L "$my_path" ]; then
	rm "$my_path"
fi

cp "$files/$id_borrar" "$my_path"
rm "$files/$id_borrar"

echo "Se ha eliminado el identificador $id_borrar y se ha restaurado el archivo original."