#!/bin/bash

# Verificar que se haya pasado un argumento
if [ $# -ne 1 ]; then
    echo "Uso: $0 id"
    exit 1
fi

id_borrar=$1
bck="$HOME/bckdir"
files="$bck/files"


# Verificar si el archivo existe en el directorio de copia de seguridad
if [ ! -e "$files/$id_borrar" ]; then
    echo "El archivo $id_borrar no existe en el directorio de copia de seguridad."
    exit 1
fi

# Obtener el nombre del archivo original del enlace simbólico
original_file=$(grep "^$id_borrar," "$bck/mypaths.txt" | cut -d ',' -f 2)

# Verificar si el enlace simbólico existe
if [ ! -e "$original_file" ]; then
    echo "El archivo original vinculado al identificador $id_borrar ya no existe."
    exit 1
fi

# Eliminar el enlace simbólico
unlink "$files/$id_borrar"

echo $(ls -l /home/pablozar12)
exit 0
# Reemplazar el enlace simbólico con el archivo original
cp "$original_file" "$files/$id_borrar"

echo "Se ha eliminado el identificador $id_borrar y se ha restaurado el archivo original."