#!/bin/bash

bck="$HOME/bckdir"

# Check if bckdir exist
if [ ! -d "$bck" ]; then
    echo "El directorio $bck no existe, por lo que no se lista ninguna información"
    exit 1
fi

# Check if mypaths.txt exists
if [ ! -f "$bck/mypaths.txt" ]; then
    echo "El fichero $bck/mypaths.txt no existe, por lo que no se lista ninguna información"
    exit 1
fi

cat "$bck/mypaths.txt"